### PR TITLE
License

### PR DESCRIPTION
**Pull request by yonojoy**
I think the original author [made the code available under MPL](https://github.com/andremussche/DelphiWebsockets/issues/2). Your (chuacw) modifications however, seem to be released under GPL. 

I really appreciate your work and would like to base my code on your fork. But I would like to use the code in a closed-source project. Therefore I would like to ask you, if you would consider to dual-license your work. That way the whole library could be available under a dual-license GPL / MPL and your work could be used in non-GPLed code.

(I choose to create a pull request because I found no clean other way to contact you via github.)

### CODE REVIEW

**Comment by chuacw** [comment]
If you'd like to use this in a closed source project, please provide your email, and I'd reach out to you.

**Comment by yonojoy** [comment]
I think, you misunderstood my intent. I am not interested in a short term solution regarding web sockets for Delphi in a closed source project of mine.


I know, there are several commercial solutions:
* [esegece](https://www.esegece.com/help/sgcWebSockets/)
* [DevArt](https://www.devart.com/sbridge/delphi-websocket-client-component.html)
* [IPWorks](https://learndelphi.org/de/build-a-robust-scalable-real-time-websocket-client-server/)

But I was looking for an open source solution. I found several implementations:

* https://github.com/fajar-khairil/ics-websockets - No SSL support
* https://github.com/stijnsanders/xxm/blob/master/Delphi/bin/public/xxmWebSocket.pas - part of another project (XXM)
* `IdWebSocketSimpleClient.pas` in several incarnations (see https://github.com/IndySockets/Indy/issues/201) - with several problems

[Delphi WebSockets](https://github.com/andremussche/DelphiWebsockets) looked most promising so far. But it is outdated and not maintained anymore.

So I inspected the forks and found your fork (https://github.com/chuacw/WebSockets) to be the most promising. I tried the lib in an example project and it worked. 
 
I am sure, that there will be a solid open source solution in the future, because web sockets emerged into an important technology. 
My goal is to bet on the solution that will finally suceed/dominate. I am pretty sure, that I will loose my bet, if I set on a soley GPLed solution. And I also would like to be able to use one library for open source as well as closed source projects.
Therefore my question, if you would consider to relicense your work under a license that is not so restrictive with respect to closed source software (eg. MPL, LGPL).

**Comment by yonojoy** [comment]
@chuacw Hi, I kindly wanted to ask, if you considered my question. It will determine which fork / project I will use for further tinkering. And of course it is completely fine, whatever you decide: your code = your decision. I just had to ask 'cause your additions would clearly be a win for the library.

**Comment by chuacw** [comment]
> I think, you misunderstood my intent

[See response](https://github.com/chuacw/WebSockets/pull/2#issuecomment-1890849770)

**Comment by yonojoy** [comment]
@chuacw OK, just to sum up things (English is not my native language): I think that leaves room for two interpretations:

**Interpretation 1:**
You _can't_ imagen to contribute your code to an MPL/LGPL effort to provide a WebSockets library for Delphi.
You would however consider to license your code for a commercial project (if that would be my intention).

**Interpretation 2:** 
You _can_ imagen to contribute your code to an MPL/LGPL effort to provide a WebSockets library for Delphi. But you want to discuss this only in private mail.


Could you please give me a hint on that one?

**Pull request closed without merging**
